const paragraphs = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet est placerat in egestas erat imperdiet sed euismod. Ultricies integer quis auctor elit sed vulputate mi. Ut porttitor leo a diam sollicitudin tempor id. Et leo duis ut diam quam. Enim tortor at auctor urna nunc id cursus. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Neque volutpat ac tincidunt vitae. Pretium lectus quam id leo in vitae turpis. Tristique sollicitudin nibh sit amet. Vitae congue mauris rhoncus aenean vel. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Bibendum enim facilisis gravida neque convallis a cras. Nisl purus in mollis nunc sed id semper risus. Duis tristique sollicitudin nibh sit amet.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra accumsan in nisl nisi scelerisque eu. Proin libero nunc consequat interdum. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Maecenas pharetra convallis posuere morbi leo. Gravida in fermentum et sollicitudin. Placerat in egestas erat imperdiet sed euismod nisi porta. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Et ultrices neque ornare aenean euismod elementum. Sed nisi lacus sed viverra tellus in.",

"Consectetur lorem donec massa sapien faucibus. Amet mauris commodo quis imperdiet. Pretium vulputate sapien nec sagittis aliquam. Quis hendrerit dolor magna eget. Nisl nunc mi ipsum faucibus vitae aliquet. Sit amet est placerat in egestas erat. Magna fermentum iaculis eu non diam phasellus. Scelerisque eu ultrices vitae auctor. Morbi tristique senectus et netus et malesuada fames ac. Proin nibh nisl condimentum id venenatis. Enim ut tellus elementum sagittis vitae et. Nam at lectus urna duis convallis. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Adipiscing elit ut aliquam purus. Pellentesque habitant morbi tristique senectus. Vitae suscipit tellus mauris a diam maecenas sed enim. Facilisi morbi tempus iaculis urna. Euismod elementum nisi quis eleifend quam adipiscing.",

"Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nulla malesuada pellentesque elit eget gravida cum. Nulla pharetra diam sit amet. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Sodales ut etiam sit amet nisl. Lectus proin nibh nisl condimentum id venenatis a condimentum vitae. Eget velit aliquet sagittis id consectetur purus ut faucibus. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Vitae nunc sed velit dignissim. Tincidunt augue interdum velit euismod. Facilisi morbi tempus iaculis urna id volutpat lacus. Cras ornare arcu dui vivamus arcu. Magna fringilla urna porttitor rhoncus. Dui accumsan sit amet nulla facilisi. Mauris sit amet massa vitae.",

"Eu facilisis sed odio morbi quis commodo odio aenean. Sed augue lacus viverra vitae congue eu consequat ac. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Eget sit amet tellus cras adipiscing enim eu. Sed sed risus pretium quam. Sed felis eget velit aliquet. Accumsan sit amet nulla facilisi morbi. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Tincidunt ornare massa eget egestas purus viverra. Hac habitasse platea dictumst vestibulum rhoncus.",

"Ultrices eros in cursus turpis massa tincidunt. Lacus vestibulum sed arcu non odio euismod. Lacus luctus accumsan tortor posuere ac ut. Adipiscing at in tellus integer. Feugiat nibh sed pulvinar proin gravida. Justo eget magna fermentum iaculis eu non. A condimentum vitae sapien pellentesque habitant. Mattis rhoncus urna neque viverra justo nec ultrices. Tincidunt tortor aliquam nulla facilisi cras. Ipsum dolor sit amet consectetur. Dui nunc mattis enim ut tellus elementum sagittis. Consectetur libero id faucibus nisl tincidunt. Imperdiet sed euismod nisi porta lorem. Ipsum a arcu cursus vitae congue mauris.",

"Ut sem viverra aliquet eget sit. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Pellentesque massa placerat duis ultricies lacus sed. Placerat vestibulum lectus mauris ultrices. Mauris cursus mattis molestie a iaculis at erat pellentesque. Et tortor at risus viverra. Quis auctor elit sed vulputate mi sit amet mauris. Turpis massa sed elementum tempus. Sit amet nulla facilisi morbi tempus. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Velit scelerisque in dictum non consectetur a. Vitae sapien pellentesque habitant morbi tristique senectus. Turpis cursus in hac habitasse platea dictumst. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Vitae elementum curabitur vitae nunc. Arcu felis bibendum ut tristique et.",

"Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Vestibulum morbi blandit cursus risus at. Pharetra convallis posuere morbi leo urna molestie at elementum. Pellentesque nec nam aliquam sem et tortor consequat id. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Interdum velit laoreet id donec ultrices tincidunt. Integer vitae justo eget magna fermentum. Sed odio morbi quis commodo odio. Enim praesent elementum facilisis leo. Et tortor consequat id porta nibh venenatis cras. Turpis egestas pretium aenean pharetra magna ac. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Elementum eu facilisis sed odio morbi quis commodo odio. Nec tincidunt praesent semper feugiat nibh. Sed blandit libero volutpat sed cras ornare arcu dui.",

"Tristique senectus et netus et malesuada fames ac. Massa tincidunt dui ut ornare lectus sit amet est placerat. Eget nullam non nisi est sit amet. Nunc sed augue lacus viverra vitae congue eu. Felis donec et odio pellentesque diam volutpat. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Amet nisl suscipit adipiscing bibendum est ultricies integer. Orci eu lobortis elementum nibh tellus. Sed enim ut sem viverra aliquet eget. Bibendum est ultricies integer quis auctor. Aliquam ut porttitor leo a. Nunc sed augue lacus viverra vitae congue eu consequat ac. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Mi quis hendrerit dolor magna eget. Nisl pretium fusce id velit ut tortor pretium viverra. Morbi enim nunc faucibus a. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Pellentesque nec nam aliquam sem et tortor consequat id porta.",

"Pellentesque pulvinar pellentesque habitant morbi tristique senectus. Tortor at risus viverra adipiscing at in tellus integer feugiat. Massa sed elementum tempus egestas sed sed risus pretium quam. Nisl nunc mi ipsum faucibus vitae aliquet nec. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Malesuada fames ac turpis egestas maecenas pharetra convallis. Lorem ipsum dolor sit amet. Eget dolor morbi non arcu risus quis varius quam. Integer eget aliquet nibh praesent tristique magna sit amet. Odio eu feugiat pretium nibh ipsum consequat nisl. At auctor urna nunc id cursus. Et egestas quis ipsum suspendisse ultrices gravida. Enim ut tellus elementum sagittis. Convallis posuere morbi leo urna molestie at elementum. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Lectus mauris ultrices eros in cursus turpis. Amet nisl purus in mollis. Tincidunt eget nullam non nisi est sit. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Pellentesque diam volutpat commodo sed egestas egestas.",

"Turpis nunc eget lorem dolor sed. Viverra justo nec ultrices dui sapien. Natoque penatibus et magnis dis parturient montes nascetur. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Massa sapien faucibus et molestie. Molestie at elementum eu facilisis sed. Enim sit amet venenatis urna cursus eget nunc. Bibendum at varius vel pharetra vel turpis. Integer eget aliquet nibh praesent tristique magna sit amet purus. Senectus et netus et malesuada fames ac turpis. Ante in nibh mauris cursus mattis molestie a. Amet consectetur adipiscing elit pellentesque. Blandit aliquam etiam erat velit. Sed libero enim sed faucibus. Fusce ut placerat orci nulla pellentesque dignissim. Dictum at tempor commodo ullamcorper. Orci eu lobortis elementum nibh tellus.",

"Amet consectetur adipiscing elit pellentesque habitant morbi. Enim blandit volutpat maecenas volutpat blandit. Bibendum neque egestas congue quisque egestas diam. Sed elementum tempus egestas sed. Lectus quam id leo in vitae turpis massa sed elementum. Sit amet risus nullam eget felis eget nunc lobortis mattis. Morbi enim nunc faucibus a. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Et magnis dis parturient montes nascetur. Integer eget aliquet nibh praesent tristique magna sit amet purus. Augue mauris augue neque gravida in. Sed nisi lacus sed viverra tellus in hac habitasse platea. Arcu non sodales neque sodales ut etiam sit. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Blandit turpis cursus in hac habitasse platea.",

"Etiam non quam lacus suspendisse faucibus. In vitae turpis massa sed elementum tempus. Pharetra sit amet aliquam id diam. Vulputate dignissim suspendisse in est ante in nibh mauris. Purus ut faucibus pulvinar elementum integer enim. Tempor nec feugiat nisl pretium fusce. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Lacus viverra vitae congue eu consequat. Dui id ornare arcu odio ut sem nulla. Odio facilisis mauris sit amet massa vitae. Eros donec ac odio tempor orci dapibus. In cursus turpis massa tincidunt dui ut ornare lectus sit. Mattis aliquam faucibus purus in massa tempor nec.",

"Nisl rhoncus mattis rhoncus urna neque viverra. Quam lacus suspendisse faucibus interdum posuere. Sapien faucibus et molestie ac. Varius duis at consectetur lorem. Nec ullamcorper sit amet risus nullam eget felis eget nunc. Tortor consequat id porta nibh venenatis cras sed felis. Arcu odio ut sem nulla. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Nisi porta lorem mollis aliquam. Quis risus sed vulputate odio ut enim. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Nulla pellentesque dignissim enim sit amet venenatis urna. Eget lorem dolor sed viverra ipsum. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Sed tempus urna et pharetra pharetra. Amet est placerat in egestas erat imperdiet sed. Nec feugiat nisl pretium fusce id velit. Fusce ut placerat orci nulla pellentesque. Quis enim lobortis scelerisque fermentum dui faucibus.",

"Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Convallis tellus id interdum velit laoreet id. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Odio euismod lacinia at quis risus. Morbi tristique senectus et netus et. Ante in nibh mauris cursus mattis molestie a iaculis at. A condimentum vitae sapien pellentesque habitant morbi tristique. Lorem dolor sed viverra ipsum nunc aliquet. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Sit amet nulla facilisi morbi tempus iaculis urna id. Sed pulvinar proin gravida hendrerit lectus a. Sed id semper risus in hendrerit gravida.",

"In nulla posuere sollicitudin aliquam ultrices sagittis orci. Dignissim suspendisse in est ante in. Elementum nibh tellus molestie nunc non blandit massa enim. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Lorem donec massa sapien faucibus. Posuere morbi leo urna molestie at elementum. Accumsan tortor posuere ac ut consequat semper viverra nam libero. A lacus vestibulum sed arcu non odio. Sit amet volutpat consequat mauris nunc congue nisi vitae. Amet nisl suscipit adipiscing bibendum. Cursus metus aliquam eleifend mi in nulla posuere. Mattis aliquam faucibus purus in massa tempor. Massa massa ultricies mi quis hendrerit dolor magna eget est. Donec adipiscing tristique risus nec feugiat in fermentum. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Volutpat sed cras ornare arcu dui vivamus arcu. Pharetra pharetra massa massa ultricies mi quis hendrerit. Nunc congue nisi vitae suscipit tellus mauris a diam. Euismod in pellentesque massa placerat duis ultricies lacus sed.",

"Nulla facilisi cras fermentum odio eu feugiat. Porttitor leo a diam sollicitudin tempor id. In mollis nunc sed id semper risus in hendrerit gravida. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Et malesuada fames ac turpis egestas integer eget. Morbi tincidunt augue interdum velit euismod in. Augue lacus viverra vitae congue eu consequat ac felis donec. Nibh tortor id aliquet lectus proin nibh. Sit amet facilisis magna etiam. Tellus elementum sagittis vitae et leo duis ut diam quam. Elementum eu facilisis sed odio morbi quis. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Hac habitasse platea dictumst vestibulum rhoncus. Eget sit amet tellus cras adipiscing. At quis risus sed vulputate odio ut enim blandit. Nisl vel pretium lectus quam id leo in vitae turpis. Bibendum enim facilisis gravida neque convallis a cras semper. Risus at ultrices mi tempus imperdiet. Fermentum iaculis eu non diam. Mattis rhoncus urna neque viverra justo nec ultrices.",

"Vitae auctor eu augue ut lectus arcu. Ultrices gravida dictum fusce ut placerat orci. Est placerat in egestas erat imperdiet. Risus nullam eget felis eget. Amet nisl suscipit adipiscing bibendum est ultricies. Vitae turpis massa sed elementum tempus egestas sed sed risus. Ullamcorper dignissim cras tincidunt lobortis feugiat. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Nunc sed velit dignissim sodales. Morbi tincidunt augue interdum velit euismod in pellentesque. Cursus in hac habitasse platea dictumst quisque sagittis. Varius vel pharetra vel turpis nunc eget lorem. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Maecenas pharetra convallis posuere morbi leo urna. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Tortor posuere ac ut consequat. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.",

"Egestas purus viverra accumsan in nisl nisi scelerisque. Pellentesque habitant morbi tristique senectus et netus et. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Penatibus et magnis dis parturient montes. Nec feugiat nisl pretium fusce id velit ut. Interdum velit laoreet id donec ultrices tincidunt arcu. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Viverra ipsum nunc aliquet bibendum enim facilisis. Morbi tincidunt augue interdum velit euismod in pellentesque. Elementum pulvinar etiam non quam lacus suspendisse. Pellentesque adipiscing commodo elit at imperdiet dui. Viverra accumsan in nisl nisi scelerisque eu ultrices. Imperdiet proin fermentum leo vel. Commodo ullamcorper a lacus vestibulum sed arcu. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Leo urna molestie at elementum eu. Tristique senectus et netus et malesuada fames ac. Turpis cursus in hac habitasse platea dictumst.",

"Faucibus vitae aliquet nec ullamcorper sit amet. Amet consectetur adipiscing elit duis tristique sollicitudin. Molestie nunc non blandit massa enim nec dui. Eget velit aliquet sagittis id consectetur. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Ut tellus elementum sagittis vitae. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Quis vel eros donec ac odio tempor orci dapibus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Volutpat odio facilisis mauris sit amet massa. Et leo duis ut diam quam nulla porttitor massa id. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Aliquam ultrices sagittis orci a scelerisque purus. Libero nunc consequat interdum varius sit amet.",

"Mauris vitae ultricies leo integer malesuada nunc vel risus. Vitae congue eu consequat ac felis donec et odio. Risus in hendrerit gravida rutrum quisque. Duis at tellus at urna condimentum mattis. Facilisis leo vel fringilla est ullamcorper eget. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Natoque penatibus et magnis dis parturient montes nascetur. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Tristique senectus et netus et malesuada fames ac. Diam maecenas ultricies mi eget. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Pretium aenean pharetra magna ac. Id interdum velit laoreet id.",
];

const texts=[
  'varius', 'duis', 'at', 'consectetur', 'lorem', 'donec', 'massa', 'sapien', 'faucibus', 'et', 'molestie', 'mac', 'feugiat', 'sed', 'lectus', 'vestibulum', 'mattis', 'ullamcorper', 'velit', 'sed', 'ullamcorper', 'morbi', 'tincidunt', 'ornare', 'massa', 'eget', 'egestas', 'purus', 'viverra', 'accumsan', 'in', 'nisl', 'nisi', 'scelerisque', 'eu', 'ultrices', 'vitae', 'auctor', 'eu', 'augue', 'ut', 'lectus', 'arcu', 'bibendum', 'at', 'varius', 'vel', 'pharetra', 'vel', 'turpis', 'ultrices', 'dui', 'sapien', 'eget', 'mi', 'proin', 'sed', 'libero', 'enim', 'sed', 'faucibus', 'turpis', 'in', 'eu', 'mi', 'bibendum', 'neque', 'egestas', 'congue', 'quisque', 'egestas', 'diam', 'in', 'arcu', 'cursus', 'euismod', 'quis', 'viverra', 'nibh', 'cras', 'pulvinar'
]

export { paragraphs, texts };